language: php

php:
  - 7.0

sudo: required

services:
  - docker

before_install:
   - docker build -t edamov/pushok:7.0 .

script:
  - docker run edamov/pushok:7.0 /bin/sh -c "cd /home/pushok; php /composer.phar update ${COMPOSER_FLAGS} --no-interaction --prefer-dist; vendor/bin/phpcs --standard=psr2 src/; vendor/bin/phpunit --coverage-clover build/logs/clover.xml;"
